# Generated by Django 5.0.4 on 2024-04-17 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('director_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('release', models.IntegerField()),
                ('rating', models.FloatField()),
                ('vote', models.FloatField(max_length=10)),
                ('unit', models.CharField(max_length=1, null=True)),
                ('duration', models.CharField(max_length=10)),
                ('synopsis', models.TextField()),
                ('link', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_250_movies.director')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_250_movies.movie')),
            ],
        ),
    ]
