# Generated by Django 5.0.4 on 2024-04-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_250_movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedirector',
            name='director_id',
        ),
        migrations.RemoveField(
            model_name='moviedirector',
            name='movie_id',
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('name', 'release')},
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='MovieDirector',
        ),
    ]
